services:
  master:
    image: redis:7.2.4
    container_name: redis-master
    command: redis-server --appendonly yes
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  slave1: 
    image: redis:7.2.4
    restart: always
    command: redis-server --appendonly yes --slaveof redis-master 6379
    ports:
      - 6381:6379
    depends_on:
      master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    
  slave2: 
    image: redis:7.2.4
    restart: always
    command: redis-server --appendonly yes --slaveof redis-master 6379
    ports:
      - 6382:6379
    depends_on:
      master:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  sentinel1:
    image: redis:7.2.4
    restart: always
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/etc/redis/sentinel.conf
    ports:
      - 26380:26379
    depends_on:
      master:
        condition: service_healthy
    
  sentinel2:
    image: redis:7.2.4
    restart: always
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/etc/redis/sentinel.conf
    depends_on:
      master:
        condition: service_healthy
  sentinel3:
    image: redis:7.2.4
    restart: always
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/etc/redis/sentinel.conf
    ports:
      - 26379:26379
    depends_on:
      master:
        condition: service_healthy    
  
  
networks: 
  default:
    name: redis-network
    driver: bridge