services:

  wordpress:
    image: wordpress
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: mywordpressuser
      WORDPRESS_DB_PASSWORD: mywordpresspass
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wordpress:/var/www/html

  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=mywordpressuser
      - MYSQL_PASSWORD=mywordpresspass
      - MYSQL_ROOT_PASSWORD=Shendongfa!1
    volumes:
      - ./mysqlvarlib:/var/lib/mysql
    healthcheck:
      # test: mysql -u root -pShendongfa!1 -e "select 1"
      test: mysql --user=root --password='Shendongfa!1' -e "select 1"
      interval: 10s
      timeout: 5s
      retries: 10